services:
  backend:
    build:
      context: ./paylegend
    container_name: paylegend-api
    ports:
      - "8000:8000"  # Ajuste a porta conforme necessário
    volumes:
      - ./paylegend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=357789
      - RABBITMQ_HOST=queue
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=357789

  db:
    image: mariadb:11.5-rc
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'MzYgODMgNzYgZmEgNzIgODIgZDkgYWEgYzggZjcg'
      MYSQL_DATABASE: paylegend
      MYSQL_USER: user
      MYSQL_PASSWORD: '357789'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  queue:
    image: rabbitmq:4.0-rc-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Porta para acessar a interface de administração do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: '357789'
    volumes:
      - queue_data:/var/lib/rabbitmq

volumes:
  db_data:
  queue_data:
