name: Deploy to Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Sync files to Droplet
      uses: burnett01/rsync-deployments@5.1
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SERVER_IP: "174.138.86.195"
        USERNAME: "root"
        LOCAL_DIR: "./"
        REMOTE_DIR: "/root/paylegend"
