name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master  # Ou a branch que deseja usar para o deploy automático

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}  # Adicione o IP da Droplet em Settings > Secrets
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Comandos de deploy, como copiar arquivos ou atualizar dependências
            rsync -avz --delete ./ /root/paylegend
            cd /root/paylegend
            # Adicione outros comandos necessários, como `composer install`, `php artisan migrate`, etc.
