name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Files to Droplet
        run: |
          scp -r -o StrictHostKeyChecking=no ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/root/paylegend

      - name: Run Post-Deploy Commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /root/paylegend
            # Adicione aqui os comandos necessários para o seu ambiente, como:
            # composer install --no-dev --optimize-autoloader
            # php artisan migrate --force
            # systemctl restart apache2  # Ou qualquer outro serviço
          EOF
